/**
 * Matric-number normalization/validation shared by the registration UI, the
 * signup server action, the profile-modal edit action, and the export
 * filename sanitizer. Pure — Node-unit-testable.
 *
 * Stored shape contract (mirrors the 0027 CHECK constraint): EXACTLY 6 DIGITS
 * (institutional format). Whitespace typed around/by the number is deleted
 * before validation; anything else (letters, dashes) is rejected.
 *
 * The 99xxxx range is RESERVED for system-generated backfill numbers
 * (migration 0027 assigns them to pre-existing students) — user-chosen values
 * in that range are rejected so they can never collide with generated ones.
 */

export const MATRIC_SHAPE = /^[0-9]{6}$/;
export const MATRIC_RESERVED_PREFIX = /^99[0-9]{4}$/;

export type MatricFailure =
  | "empty"
  | "invalid"
  | "reserved"
  | "too_long";

export type NormalizeResult =
  | { ok: true; value: string }
  | { ok: false; reason: MatricFailure };

/** Trim → delete ALL internal whitespace. Digits only beyond this point. */
export function normalizeMatricShape(raw: string): string {
  return raw.trim().replace(/\s+/g, "");
}

export function normalizeMatric(raw: string): NormalizeResult {
  if (typeof raw !== "string") return { ok: false, reason: "invalid" };
  const value = normalizeMatricShape(raw);
  if (value.length === 0) return { ok: false, reason: "empty" };
  if (!/^[0-9]+$/.test(value)) return { ok: false, reason: "invalid" };
  if (value.length > 6) return { ok: false, reason: "too_long" };
  if (!MATRIC_SHAPE.test(value)) return { ok: false, reason: "invalid" };
  if (MATRIC_RESERVED_PREFIX.test(value)) return { ok: false, reason: "reserved" };
  return { ok: true, value };
}

/** True when a stored matric was system-generated by migration 0027. */
export function isSystemAssignedMatric(matricNo: string | null | undefined): boolean {
  if (!matricNo) return false;
  return MATRIC_RESERVED_PREFIX.test(matricNo);
}

const FILENAME_ALLOWED = /[^A-Za-z0-9._ -]/g;
const FILENAME_MAX = 80;

/**
 * Whitelist-sanitize free text for use inside a Content-Disposition filename:
 * strip disallowed chars (CRLF would throw in undici Headers; quotes,
 * backslashes, and control chars corrupt attachment parsing), collapse
 * whitespace/separators, cap length. Empty result falls back to "quiz".
 */
export function sanitizeFilenamePart(title: string | null | undefined): string {
  const cleaned = (title ?? "")
    .replace(FILENAME_ALLOWED, " ")
    .replace(/\s+/g, " ")
    .trim()
    // Collapse separator runs so titles don't end up as "----".
    .replace(/^[ ._\-]+|[ ._\-]+$/g, "");
  if (cleaned.length === 0) return "quiz";
  return cleaned.length > FILENAME_MAX ? cleaned.slice(0, FILENAME_MAX).trimEnd() : cleaned;
}
