import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Supabase local dev artifacts (auto-generated):
    "supabase/.temp/**",
    "supabase/.branches/**",
    // Test coverage output (auto-generated):
    "coverage/**",
    // Vendored MediaPipe runtime + hand-landmarker model (auto-generated by
    // `npm run vendor:mediapipe`, integrity-checked by `npm run verify:mediapipe`):
    "public/mediapipe/**",
    "public/models/**",
    // Playwright test artifacts (auto-generated):
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
