import { test, expect } from "@playwright/test";
import { registerUser, E2E_PASSWORD } from "./helpers";

/**
 * E19 — Student-authored quiz generated by AI (plan F1).
 * The student creates a practice quiz and generates questions from PASTED
 * text via the mock AI server (playwright.config webServer). The mock returns
 * a FIXED payload, so assertions target its question count/prompts — never
 * the requested count.
 */

const stamp = Date.now();
const STUDENT = `ai-stu-${stamp}@e2e.test`;
const QUIZ_TITLE = `AI Practice ${stamp}`;

test.describe.configure({ mode: "serial" });

test("student generates practice questions from pasted text via AI", async ({ page }) => {
  await registerUser(page, STUDENT, "student", "");

  // Create the quiz shell → editor.
  await page.goto("/student/my-quizzes");
  await page.getByRole("link", { name: /create quiz/i }).click();
  await page.getByLabel("Title").fill(QUIZ_TITLE);
  await page.getByRole("button", { name: /create quiz/i }).click();
  await page.waitForURL(/\/student\/my-quizzes\/[^/]+\/edit/);

  // Open the AI dialog (student mode: steering/format/mode controls hidden).
  await page.getByRole("button", { name: /generate with ai/i }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toBeVisible();
  await expect(dialog.getByText(/step 1 of 2/i)).toBeVisible();

  // Paste-text leg: fill the paste area and continue past extraction.
  const paste = dialog.getByLabel(/paste your material/i);
  await paste.fill(
    "Photosynthesis is the process by which plants convert light energy into " +
      "chemical energy. Chlorophyll absorbs sunlight in the chloroplasts. " +
      "The Calvin cycle fixes carbon dioxide into glucose. Mitochondria are " +
      "the powerhouse of the cell and produce ATP through respiration.",
  );
  await dialog.getByRole("button", { name: /use pasted text/i }).click();

  // Step 2: student-mode controls — difficulty present, steering absent.
  await expect(dialog.getByText(/difficulty level/i)).toBeVisible();
  await expect(dialog.getByText(/custom ai focus/i)).toBeHidden();

  // Generate (mock AI serves a fixed valid quiz) → editor refreshes with rows.
  await dialog.getByRole("button", { name: /generate quiz/i }).click();
  await page.waitForURL(/\/student\/my-quizzes\/[^/]+\/edit/, { timeout: 60_000 });

  // Mock payload = fixed set; assert its known prompts landed in the editor.
  await expect(
    page.locator("li", { hasText: /velocity/i }).first(),
  ).toBeVisible({ timeout: 30_000 });
});

test("second generation appends into the same quiz", async ({ page }) => {
  await page.goto("/login");
  await page.getByLabel(/Email/).fill(STUDENT);
  await page.getByLabel("Password", { exact: true }).fill(E2E_PASSWORD);
  await page.getByRole("button", { name: /sign in/i }).click();
  await page.waitForURL(/\/(student|lecturer)\//, { timeout: 30_000 });

  await page.goto("/student/my-quizzes");
  // Titles are plain text; the row's Edit (pencil) link opens the editor.
  const row = page.locator("li", { hasText: QUIZ_TITLE });
  await row.getByRole("link", { name: /edit/i }).first().click();
  await page.waitForURL(/\/student\/my-quizzes\/[^/]+\/edit/);

  const before = await page.locator("ol > li").count();
  const dialog2 = page.getByRole("dialog");
  await page.getByRole("button", { name: /generate with ai/i }).click();
  await expect(dialog2).toBeVisible();
  const paste = dialog2.getByLabel(/paste your material/i);
  await paste.fill(
    "Newton's three laws describe motion. Inertia keeps objects at rest. " +
      "Force equals mass times acceleration. Every action has an equal and " +
      "opposite reaction. Gravity accelerates falling objects.",
  );
  await dialog2.getByRole("button", { name: /use pasted text/i }).click();
  await dialog2.getByRole("button", { name: /generate quiz/i }).click();
  await page.waitForURL(/\/student\/my-quizzes\/[^/]+\/edit/, { timeout: 60_000 });

  // Append semantics: total grows beyond the first batch.
  await expect
    .poll(async () => page.locator("ol > li").count(), { timeout: 30_000 })
    .toBeGreaterThan(before);
});
